'use client';

import { createContext, useEffect, useState } from 'react';
import { Inter } from 'next/font/google';
// import type { Metadata } from 'next';
import './globals.css';
import CustomProvider from './redux/provider';

import { THEMES } from '../constants';
import { IThemeContext } from '../types/AppTypes';
import ErrorBoundary from '../components/ErrorBoundary/ErrorBoundary';
// import { ThemeProvider } from '../components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export const ThemeContext = createContext<IThemeContext>({
  theme: THEMES.DARK,
  setTheme: () => {},
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [theme, setTheme] = useState(THEMES.DARK);
  useEffect(() => {
    const rootElement = document.getElementById('root');
    if (rootElement) {
      rootElement.className = theme === THEMES.DARK ? 'dark' : 'light';
    }
  }, [theme]);

  return (
    <html lang="en">
      <ThemeContext.Provider value={{ theme, setTheme }}>
        {/* <ThemeProvider> */}
        <ErrorBoundary>
          <head>
            <title>Star Wars</title>
          </head>
          <body className={inter.className}>
            <CustomProvider>
              <main id="root">{children}</main>
            </CustomProvider>
          </body>
        </ErrorBoundary>
        {/* </ThemeProvider> */}
      </ThemeContext.Provider>
    </html>
  );
}
